"""
generate_risk_report.py - risk_report.md auto-generate (Issue #8)

Pipeline: findings.json -> quantum_mapper -> qubit cost -> markdown.
Usage: python generate_risk_report.py [findings.json] [--out PATH] [--force]
Same input => same output (koi timestamp nahi), taaki rerun diff ho sake.
"""
import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))
from src import quantum_mapper as qm  # noqa: E402

# Pehli line ka marker: isse pata chalta hai file script ne banayi hai.
MARKER = "<!-- AUTO-GENERATED by generate_risk_report.py -->"


def load_qubit_fn():
    """Yatharth ka estimator mile to wahi, warna 2n + 3 fallback."""
    sys.path.insert(0, str(ROOT / "notebook"))
    try:
        from qubit_estimator import shor_logical_qubits
        return shor_logical_qubits, "notebook/qubit_estimator.py"
    except ImportError:
        def fallback(n_bits):
            return 2 * n_bits + 3
        return fallback, "built-in fallback (2n + 3)"


def cell(value):
    """Table cell: None -> '-', aur '|' escape (warna table toot jata hai)."""
    if value is None:
        return "-"
    return str(value).replace("|", "\\|").replace("\n", " ")


def add_table(lines, headers, rows, empty_msg):
    """Markdown table jodo; rows na ho to empty_msg likho."""
    if not rows:
        lines.append(empty_msg)
        return
    lines.append("| " + " | ".join(headers) + " |")
    lines.append("|" + "|".join("---" for _ in headers) + "|")
    for row in rows:
        lines.append("| " + " | ".join(cell(c) for c in row) + " |")


def loc(item):
    """'file:line' string."""
    return f"{item.get('file')}:{item.get('line')}"


def finding_key(item):
    """Fixed sort order, taaki report har run pe same rahe."""
    return (str(item.get("project", "")), str(item.get("file", "")),
            item.get("line") or 0)


def flag_key(flag):
    return (str(flag.get("file")), flag.get("line") or 0)


def build(data, qubits):
    """Poora report text banao."""
    mapped = sorted(qm.map_findings(data["findings"]), key=finding_key)
    edge = data.get("edge_cases", {})
    projects = sorted({m.get("project", "?") for m in mapped} | set(edge))
    out = [MARKER, "# Risk Report", "",
           "Auto-generated from findings.json, quantum_mapper and the "
           "qubit estimator.",
           "All qubit counts are LOGICAL qubits.", ""]

    # 1. Summary: har project ka ek row.
    out += ["## 1. Summary", ""]
    rows = []
    for p in projects:
        ms = [m for m in mapped if m.get("project") == p]
        prims = defaultdict(int)
        for m in ms:
            name = m.get("canonical_primitive") or m.get("primitive")
            prims[str(name)] += 1
        rsa = [m for m in ms if m.get("canonical_primitive") == "RSA"]
        unresolved = sum(1 for m in rsa if not m.get("size_used_bits"))
        e = edge.get(p, {})
        rows.append([p, len(ms),
                     ", ".join(f"{k}: {v}" for k, v in sorted(prims.items())),
                     len(rsa), unresolved,
                     len(e.get("padding", [])),
                     len(e.get("indirect_usage", []))])
    add_table(out, ["Project", "Findings", "By primitive", "RSA findings",
                    "RSA size unresolved", "No-padding flags",
                    "Indirect usage"], rows, "No findings.")

    # 2. RSA key size + Shor qubit cost.
    # size_used_bits mapper ka final modulus size hai (modulus_bits jeetta hai).
    out += ["", "## 2. RSA key sizes and Shor qubit cost", ""]
    groups = defaultdict(list)
    for m in mapped:
        n = m.get("size_used_bits")
        if m.get("canonical_primitive") == "RSA" and isinstance(n, int):
            groups[(m.get("project", "?"), n)].append(m)
    rows = []
    for (p, n), ms in sorted(groups.items()):
        where = ", ".join(sorted({loc(m) for m in ms}))
        rows.append([p, n, len(ms), qubits(n), ms[0].get("impact"),
                     ms[0].get("post_quantum_security_bits"), where])
    add_table(out, ["Project", "Modulus bits (n)", "Findings",
                    "Logical qubits (Shor, 2n+3)", "Impact",
                    "Post-quantum security bits", "Locations"],
              rows, "No RSA key sizes resolved.")
    out.append("")
    out.append("Findings whose size is not on the flagged line (for example "
               "wrapper calls) are counted as unresolved in the summary.")

    # 3. Padding weaknesses (edge_cases se).
    out += ["", "## 3. Padding weaknesses", ""]
    rows = []
    for p in projects:
        flags = edge.get(p, {}).get("padding", [])
        for fl in sorted(flags, key=flag_key):
            rows.append([p, loc(fl), fl.get("flag"), fl.get("detail")])
    add_table(out, ["Project", "Location", "Flag", "Detail"], rows,
              "None found.")

    # 4. Indirect crypto usage.
    out += ["", "## 4. Indirect crypto usage", ""]
    rows = []
    for p in projects:
        flags = edge.get(p, {}).get("indirect_usage", [])
        for fl in sorted(flags, key=flag_key):
            rows.append([p, loc(fl), fl.get("detail")])
    add_table(out, ["Project", "Location", "Detail"], rows, "None found.")

    # 5. Non-RSA primitives (SHA, AES, ECC wagairah).
    out += ["", "## 5. Other primitives", ""]
    rows = []
    for m in mapped:
        if m.get("canonical_primitive") == "RSA":
            continue
        name = m.get("canonical_primitive") or m.get("primitive")
        rows.append([m.get("project"), loc(m), name,
                     m.get("quantum_algorithm"), m.get("impact"),
                     m.get("post_quantum_security_bits"),
                     m.get("size_used_bits")])
    add_table(out, ["Project", "Location", "Primitive", "Quantum algorithm",
                    "Impact", "Post-quantum security bits", "Size used"],
              rows, "None found.")

    # 6. Mapper ke size warnings.
    out += ["", "## 6. Size warnings", ""]
    rows = [[m.get("project"), loc(m), m.get("size_warning")]
            for m in mapped if m.get("size_warning")]
    add_table(out, ["Project", "Location", "Warning"], rows, "None.")

    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("findings", nargs="?", default="outputs/findings.json")
    ap.add_argument("--out", default="docs/risk_report.md")
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()

    data = json.loads(Path(args.findings).read_text(encoding="utf-8"))
    qubits, source = load_qubit_fn()
    out_path = Path(args.out)

    # Safety: bina marker wali (hand se likhi) file overwrite nahi karni.
    if out_path.exists() and not args.force:
        first = out_path.read_text(encoding="utf-8").splitlines()[:1]
        if first != [MARKER]:
            print(f"REFUSED: {out_path} auto-generated nahi hai.")
            print("Teammates ke hand-edits mit jayenge. --force ya --out use karo.")
            return 1

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(build(data, qubits), encoding="utf-8")
    print(f"Written: {out_path}")
    print(f"Qubit source: {source}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
