"""
generate_risk_report.py - risk_report.md auto-generate (Issue #8)

Pipeline: findings.json -> quantum_mapper -> qubit cost -> markdown.
Usage: python generate_risk_report.py [findings.json] [--out PATH] [--force]
Same input => same output (koi timestamp nahi), taaki rerun diff ho sake.
Extra sections: docs/risk_report_extra/*.md report ke end mein jud jate hain.
"""
import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))
from src import quantum_mapper as qm  # noqa: E402

# Pehli line ka marker: isse pata chalta hai file script ne banayi hai.
MARKER = "<!-- AUTO-GENERATED by generate_risk_report.py -->"
# Defaults repo root se resolve hote hain, current folder se nahi.
DEFAULT_FINDINGS = ROOT / "outputs" / "findings.json"
DEFAULT_OUT = ROOT / "docs" / "risk_report.md"
# Teammates yahan alag .md files daalein, script unhe end mein jodegi.
EXTRAS_DIR = ROOT / "docs" / "risk_report_extra"


def load_qubit_fn():
    """Yatharth ka estimator mile to wahi, warna 2n + 3 fallback."""
    notebook = str(ROOT / "notebook")
    if notebook not in sys.path:
        sys.path.insert(0, notebook)
    try:
        from qubit_estimator import shor_logical_qubits
        return shor_logical_qubits, "notebook/qubit_estimator.py"
    except ImportError:
        def fallback(n_bits):
            return 2 * n_bits + 3
        return fallback, "built-in fallback (2n + 3)"


def load_data(path):
    """findings.json padho; list aur dict dono forms chalenge."""
    raw = json.loads(Path(path).read_text(encoding="utf-8-sig"))
    if isinstance(raw, list):
        return {"findings": raw, "edge_cases": {}}
    if "findings" not in raw:
        raise ValueError("'findings' key nahi mili")
    return raw


def load_extras():
    """docs/risk_report_extra/*.md ke texts, file-naam ke order mein."""
    if not EXTRAS_DIR.is_dir():
        return []
    texts = []
    for path in sorted(EXTRAS_DIR.glob("*.md")):
        text = path.read_text(encoding="utf-8-sig").strip()
        if text:
            texts.append(text)
    return texts


def first_line(path):
    """File ki pehli line (BOM aur kharab bytes ko tolerate karke)."""
    text = Path(path).read_text(encoding="utf-8-sig", errors="replace")
    lines = text.splitlines()
    return lines[0] if lines else ""


def cell(value):
    """Table cell: None -> '-', aur '|' escape (warna table toot jata hai)."""
    if value is None:
        return "-"
    return str(value).replace("|", "\\|").replace("\n", " ")


def add_table(lines, headers, rows, empty_msg):
    """Markdown table jodo; rows na ho to empty_msg likho."""
    if not rows:
        lines.append(empty_msg)
        return
    lines.append("| " + " | ".join(headers) + " |")
    lines.append("|" + "|".join("---" for _ in headers) + "|")
    for row in rows:
        lines.append("| " + " | ".join(cell(c) for c in row) + " |")


def proj(item):
    """Project ka naam (kabhi None nahi, sorting crash na ho)."""
    return str(item.get("project") or "?")


def loc(item):
    """'file:line' string."""
    return f"{item.get('file')}:{item.get('line')}"


def finding_key(item):
    """Fixed sort order, taaki report har run pe same rahe."""
    return (proj(item), str(item.get("file", "")), item.get("line") or 0)


def flag_key(flag):
    """Edge-case flags ka fixed sort order."""
    return (str(flag.get("file")), flag.get("line") or 0)


def valid_bits(n):
    """True agar n positive int ho (bool nahi)."""
    return isinstance(n, int) and not isinstance(n, bool) and n > 0


def build(data, qubits, extras):
    """Poora report text banao."""
    mapped = sorted(qm.map_findings(data["findings"]), key=finding_key)
    edge = data.get("edge_cases", {})
    projects = sorted({proj(m) for m in mapped} | {str(k) for k in edge})
    out = [MARKER, "# Risk Report", "",
           "Auto-generated from findings.json, quantum_mapper and the "
           "qubit estimator.",
           "All qubit counts are LOGICAL qubits.", ""]

    # 1. Summary: har project ka ek row.
    out += ["## 1. Summary", ""]
    rows = []
    for p in projects:
        ms = [m for m in mapped if proj(m) == p]
        prims = defaultdict(int)
        for m in ms:
            name = m.get("canonical_primitive") or m.get("primitive")
            prims[str(name)] += 1
        rsa = [m for m in ms if m.get("canonical_primitive") == "RSA"]
        no_size = sum(1 for m in rsa if not m.get("size_used_bits"))
        e = edge.get(p, {})
        rows.append([p, len(ms),
                     ", ".join(f"{k}: {v}" for k, v in sorted(prims.items())),
                     len(rsa), no_size,
                     len(e.get("padding", [])),
                     len(e.get("indirect_usage", []))])
    add_table(out, ["Project", "Findings", "By primitive", "RSA findings",
                    "RSA findings without a size", "No-padding flags",
                    "Indirect usage"], rows, "No findings.")

    # 2. RSA key size + Shor qubit cost.
    # size_used_bits mapper ka final modulus size hai (modulus_bits jeetta hai).
    out += ["", "## 2. RSA key sizes and Shor qubit cost", ""]
    groups = defaultdict(list)
    for m in mapped:
        n = m.get("size_used_bits")
        if m.get("canonical_primitive") == "RSA" and valid_bits(n):
            groups[(proj(m), n)].append(m)
    rows = []
    for (p, n), ms in sorted(groups.items()):
        where = ", ".join(sorted({loc(m) for m in ms}))
        rows.append([p, n, len(ms), qubits(n), ms[0].get("impact"),
                     ms[0].get("post_quantum_security_bits"), where])
    add_table(out, ["Project", "Modulus bits (n)", "Findings",
                    "Logical qubits (Shor, 2n+3)", "Impact",
                    "Post-quantum security bits", "Locations"],
              rows, "No RSA key sizes resolved.")
    out += ["",
            "Qubit cost is computed for RSA only. A project listed with "
            "several sizes has call sites that use different key sizes; "
            "see the Locations column.",
            "",
            "RSA findings without a size are lines such as pow(), phi or "
            "wrapper calls, where no key size can be read."]

    # 3. Padding weaknesses (edge_cases se).
    out += ["", "## 3. Padding weaknesses", ""]
    rows = []
    for p in projects:
        flags = edge.get(p, {}).get("padding", [])
        for fl in sorted(flags, key=flag_key):
            rows.append([p, loc(fl), fl.get("flag"), fl.get("detail")])
    add_table(out, ["Project", "Location", "Flag", "Detail"], rows,
              "None found.")

    # 4. Indirect crypto usage.
    out += ["", "## 4. Indirect crypto usage", ""]
    rows = []
    for p in projects:
        flags = edge.get(p, {}).get("indirect_usage", [])
        for fl in sorted(flags, key=flag_key):
            rows.append([p, loc(fl), fl.get("detail")])
    add_table(out, ["Project", "Location", "Detail"], rows, "None found.")

    # 5. Non-RSA primitives (SHA, AES, ECC wagairah).
    out += ["", "## 5. Other primitives", ""]
    rows = []
    for m in mapped:
        if m.get("canonical_primitive") == "RSA":
            continue
        name = m.get("canonical_primitive") or m.get("primitive")
        rows.append([proj(m), loc(m), name,
                     m.get("quantum_algorithm"), m.get("impact"),
                     m.get("post_quantum_security_bits"),
                     m.get("size_used_bits")])
    if rows:
        out += ["No qubit estimate is computed for these primitives.", ""]
    add_table(out, ["Project", "Location", "Primitive", "Quantum algorithm",
                    "Impact", "Post-quantum security bits", "Size used"],
              rows, "None found.")

    # 6. Mapper ke size warnings.
    out += ["", "## 6. Size warnings", ""]
    rows = [[proj(m), loc(m), m.get("size_warning")]
            for m in mapped if m.get("size_warning")]
    add_table(out, ["Project", "Location", "Warning"], rows, "None.")

    # Teammates ke extra sections, file-naam ke order mein.
    for text in extras:
        out += ["", text]

    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser(description="Generate risk_report.md")
    ap.add_argument("findings", nargs="?", default=str(DEFAULT_FINDINGS))
    ap.add_argument("--out", default=str(DEFAULT_OUT))
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()

    try:
        data = load_data(args.findings)
    except (OSError, ValueError) as err:
        print(f"ERROR: findings padh nahi paye ({args.findings}): {err}")
        return 1

    qubits, source = load_qubit_fn()
    out_path = Path(args.out)

    # Safety: bina marker wali (hand se likhi) file overwrite nahi karni.
    if out_path.exists() and not args.force:
        if first_line(out_path) != MARKER:
            print(f"REFUSED: {out_path} auto-generated nahi hai.")
            print("Hand-edits mit jayenge. --force ya --out use karo.")
            return 1

    out_path.parent.mkdir(parents=True, exist_ok=True)
    # newline="\n": Windows aur Linux par bytes same, hash match karega.
    text = build(data, qubits, load_extras())
    out_path.write_text(text, encoding="utf-8", newline="\n")
    print(f"Written: {out_path}")
    print(f"Qubit source: {source}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
